Added QFT benchmark for PyQuEST
Roger-luo/quantum-benchmarks pull request #31
Opened 2021-01-13 03:21 UTC by codewithsk

- Added QFT benchmark for PyQuEST

2021-01-13 03:22 UTC, codewithsk commented
```
----------------------------------------------------------------------------------------------------- benchmark 'QFT': 22 tests ------------------------------------------------------------------------------------------------------
Name (time in us)                 Min                        Max                       Mean                  StdDev                     Median                     IQR            Outliers           OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_QFT[4]                    6.2259 (1.0)              33.8969 (1.01)              6.3897 (1.0)            0.3786 (1.0)               6.3712 (1.0)            0.0591 (1.0)        56;449  156,501.8542 (1.0)       21886           1
test_QFT[5]                    9.4250 (1.51)             33.4270 (1.0)               9.6585 (1.51)           0.4689 (1.24)              9.6294 (1.51)           0.0852 (1.44)      260;636  103,535.9069 (0.66)      56815           1
test_QFT[6]                   14.6381 (2.35)             47.7391 (1.43)             14.9824 (2.34)           0.5529 (1.46)             14.9468 (2.35)           0.1146 (1.94)      246;473   66,744.7789 (0.43)      34346           1
test_QFT[7]                   23.1061 (3.71)             45.2162 (1.35)             23.6377 (3.70)           0.6611 (1.75)             23.5899 (3.70)           0.1588 (2.69)      304;583   42,305.2727 (0.27)      31258           1
test_QFT[8]                   39.2268 (6.30)             91.2249 (2.73)             39.9802 (6.26)           1.0193 (2.69)             39.8718 (6.26)           0.2026 (3.43)      320;548   25,012.3970 (0.16)      16831           1
test_QFT[9]                   71.9558 (11.56)           102.2299 (3.06)             73.3496 (11.48)          1.2242 (3.23)             73.1773 (11.49)          0.2491 (4.21)      377;678   13,633.3428 (0.09)      12220           1
test_QFT[10]                 143.4856 (23.05)           194.7903 (5.83)            146.0083 (22.85)          1.9564 (5.17)            145.6430 (22.86)          0.4026 (6.81)      538;726    6,848.9272 (0.04)       6477           1
test_QFT[11]                 301.0761 (48.36)           344.7263 (10.31)           306.8476 (48.02)          2.8598 (7.55)            306.1290 (48.05)          0.8467 (14.32)     376;445    3,258.9463 (0.02)       3009           1
test_QFT[12]                 652.3710 (104.78)          701.2258 (20.98)           664.1333 (103.94)         4.4531 (11.76)           662.7114 (104.02)         3.3819 (57.19)     207;135    1,505.7219 (0.01)       1444           1
test_QFT[13]               1,448.3044 (232.63)        1,498.1283 (44.82)         1,456.9106 (228.01)         6.0284 (15.92)         1,455.9375 (228.52)         6.3754 (107.80)     152;33      686.3839 (0.00)        676           1
test_QFT[14]               3,173.3629 (509.70)        3,391.5718 (101.46)        3,230.6402 (505.60)        21.2452 (56.11)         3,226.3061 (506.39)        15.0693 (254.81)      33;26      309.5362 (0.00)        306           1
test_QFT[15]               7,021.7978 (>1000.0)       7,409.2401 (221.65)        7,130.2597 (>1000.0)       36.7941 (97.18)         7,120.0365 (>1000.0)       24.2356 (409.81)      17;13      140.2473 (0.00)        140           1
test_QFT[16]              15,763.8281 (>1000.0)      18,175.5880 (543.74)       16,285.5778 (>1000.0)      535.1104 (>1000.0)      16,104.2614 (>1000.0)      644.1020 (>1000.0)      10;3       61.4040 (0.00)         63           1
test_QFT[17]              35,265.6869 (>1000.0)      39,042.6251 (>1000.0)      36,825.8542 (>1000.0)    1,135.3649 (>1000.0)      36,630.6596 (>1000.0)    1,976.3394 (>1000.0)      11;0       27.1548 (0.00)         28           1
test_QFT[18]              78,819.3718 (>1000.0)      83,018.2326 (>1000.0)      80,897.7501 (>1000.0)    1,226.6660 (>1000.0)      80,766.6187 (>1000.0)    2,244.8724 (>1000.0)       5;0       12.3613 (0.00)         13           1
test_QFT[19]             178,191.1659 (>1000.0)     180,367.0521 (>1000.0)     179,430.7315 (>1000.0)      986.0279 (>1000.0)     179,750.8637 (>1000.0)    1,917.9862 (>1000.0)       2;0        5.5732 (0.00)          6           1
test_QFT[20]             398,260.6721 (>1000.0)     406,394.0700 (>1000.0)     403,655.8628 (>1000.0)    3,147.9998 (>1000.0)     404,414.2491 (>1000.0)    2,892.5923 (>1000.0)       1;0        2.4774 (0.00)          5           1
test_QFT[21]             928,869.4519 (>1000.0)     938,149.4550 (>1000.0)     932,839.8781 (>1000.0)    4,007.8211 (>1000.0)     931,368.4693 (>1000.0)    6,835.0802 (>1000.0)       1;0        1.0720 (0.00)          5           1
test_QFT[22]           2,036,325.4431 (>1000.0)   2,059,214.5477 (>1000.0)   2,049,473.0679 (>1000.0)    8,596.7501 (>1000.0)   2,050,353.8530 (>1000.0)   10,907.1014 (>1000.0)       2;0        0.4879 (0.00)          5           1
test_QFT[23]           4,454,272.2749 (>1000.0)   4,503,896.0953 (>1000.0)   4,487,340.3848 (>1000.0)   20,524.6159 (>1000.0)   4,492,324.2042 (>1000.0)   28,356.6568 (>1000.0)       1;0        0.2228 (0.00)          5           1
test_QFT[24]           9,545,235.6203 (>1000.0)   9,852,307.4612 (>1000.0)   9,707,566.3011 (>1000.0)  119,439.8400 (>1000.0)   9,739,679.8502 (>1000.0)  175,275.2250 (>1000.0)       2;0        0.1030 (0.00)          5           1
test_QFT[25]          20,071,759.9280 (>1000.0)  20,625,650.1428 (>1000.0)  20,290,392.6726 (>1000.0)  216,033.9784 (>1000.0)  20,294,351.8329 (>1000.0)  285,437.9553 (>1000.0)       2;0        0.0493 (0.00)          5           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

2021-01-17 17:35 UTC, Roger-luo requested changes

2021-01-17 17:35 UTC, Roger-luo commented on pyquest/benchmarks.py
> +    for i in range(nqubits//2):
why do we need swap gates here?

2021-01-17 17:35 UTC, Roger-luo commented on pyquest/benchmarks.py
> +    for i in range(nqubits//2):
this is not identical to Yao's benchmark you implemented

2021-01-17 17:45 UTC, merged